// frontend ancien/pages/login.vue
<template>
<div class="container">
    <div class="flex items-center justify-center">
        <div class="w-full">
          <img src="./images/icon2.png" alt="landing image">
        </div>
        <div class="w-full max-w-md mt-10">
            <form class="bg-white shadow-lg rounded px-12 pt-6 pb-8 mb-4" ref="loginform" >
                <!-- @csrf -->
                <img src="./images/logo.png" alt="logo image">
              <div class="text-gray-800 text-2xl flex justify-center border-b-2 py-2 mb-4">

              </div>  
                
                <div class="mb-4">
                  <label
                    class="block text-gray-700 text-sm font-normal mb-2"
                    for="username">
                    Email
                  </label>
                  <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    name="email"
                    type="email"
                    v-model="form.email"                required
                    autofocus
                    placeholder="Email"/> 
                </div>
                <div class="mb-6">
                  <label
                    class="block text-gray-700 text-sm font-normal mb-2"
                    for="password">                
                    Password
                  </label>
                  <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
                    type="password"
                    placeholder="Password"
                    name="password"
                    v-model="form.password"
                    required
                    autocomplete="current-password"/>
                </div>
                <div class="flex items-center justify-between">
                  <button class="px-4 py-2 rounded text-white inline-block shadow-lg bg-blue-500 hover:bg-blue-600 focus:bg-blue-700" type="submit" @click.prevent="login()">Sign In</button>
                  <a class="inline-block align-baseline font-normal text-sm text-blue-500 hover:text-blue-800" href="#">               
                  Forgot Password?
                  </a>
                </div>
            </form>
              <p class="text-center text-gray-500 text-xs"></p> 
        </div>
    </div>
</div>
</template>


 <script>

export default {
  middleware:'auth',
  data() {
    return {
      form: {
        email: '' ,
        password: ''
      }
    }
  },
    mounted(){
        console.log(this.$auth);
    },
  methods: {
    async login() {
      try {
        console.log(this.$auth);
        console.log('--------------------------uhukh-------------------------------');
        let response = await this.$auth.loginWith('local', { data: this.form })
        this.$auth.setUserToken(response.data.data.original.access_token)
        .then(response =>{
                    this.$router.push(
                     '/dashboard',
                    )
  
                  })
                    
        // console.log(response.data.data.original.access_token);
        console.log(this.$auth);
      } catch (err) {
        console.log(err)
      }
    }
  }
}
</script>

<!-- 
<script>
import axios from "axios";
    export default{
      auth:'guest',
      data(){
        return{
          form:{
            email: '',
            password: '',
          }
        }
      },

        methods:{
          login(){

            var that = this;       
               axios.post('http://localhost:8000/api/authentifier', this.form)
                .then(function(response){ 
                console.log(this.$auth)
                
                if (response.data.status == "error") {
                    that.error_message = response.data.message
                    that.error_champ  = response.data.data
                           } 
                    
            })
        
        }

        
            }
        }
    
</script>  -->

<style>
body{
  background-color: rgb(150, 151, 156);
}
.container{
  border: 1px solid transparent;
  background-color: #fff;
  width: 70%;
  margin-left: 15%;
  margin-top: 5%;
  border-radius: 10px;
}
form img{
  padding-left: 25%;
  width: 250px;

}
.flex{
    display: flex;
    align-items: center;
    justify-content: space-around;
    flex-wrap: wrap;
    padding: 3% ;
}

.w-full{
    flex-basis: 50%; 
    min-width: 350px;

}
</style>

// pages/auth/login.tsx
import { useState, ChangeEvent, FormEvent } from "react";
import { getSession, signIn } from "next-auth/react";
import { useRouter } from "next/navigation";
import { Toaster, toast } from "react-hot-toast";

const Login = () => {
  const [email, setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const router = useRouter();

  const handleEmailChange = (e: ChangeEvent<HTMLInputElement>) => {
    setEmail(e.target.value);
  };

  const handlePasswordChange = (e: ChangeEvent<HTMLInputElement>) => {
    setPassword(e.target.value);
  };

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    try {
      const result = await signIn("credentials", {
        email,
        password,
        redirect: false,
      });

      if (result && result.error === null) {
        const session = await getSession();
        if (session) {
          toast.success("En cours de connexion", {
            style: {
              borderRadius: "10px",
              background: "#333",
              color: "#fff",
            },
            duration: 2000,
          });
          router.push("/"); // Redirection vers la page de dashboard
        }
      } else {
        router.push("/auth/login"); // Redirection vers la page de connexion
        toast.error("La connexion a échouée !", {
          style: {
            borderRadius: "10px",
            background: "#333",
            color: "#fff",
          },
          duration: 2000,
        });
      }
    } catch (error) {
      console.error("Erreur de connexion :", error);
    }
  };

  return (
    <>
      <div className="min-h-screen bg-gray-100 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-md w-full space-y-8">
          <div>
            <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
              Connexion
            </h2>
          </div>
          <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
            <div>
              <label htmlFor="email" className="sr-only">
                Adresse email
              </label>
              <input
                id="email"
                name="email"
                type="email"
                autoComplete="email"
                required
                className="appearance-none  relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:z-10 sm:text-sm"
                placeholder="Adresse email"
                value={email}
                onChange={handleEmailChange}
              />
            </div>
            <div>
              <label htmlFor="password" className="sr-only">
                Mot de passe
              </label>
              <input
                id="password"
                name="password"
                type="password"
                autoComplete="current-password"
                required
                className="appearance-none  relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:z-10 sm:text-sm mt-3"
                placeholder="Mot de passe"
                value={password}
                onChange={handlePasswordChange}
              />
            </div>
            <div>
              <button
                type="submit"
                className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
              >
                Se connecter
              </button>
            </div>
          </form>
        </div>
      </div>

      <div>
        <Toaster />
      </div>
    </>
  );
};

export default Login;
